# Generated by Django 5.2.17 on 2026-10-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'Según mi dispositivo'), ('light', 'Modo claro'), ('dark', 'Modo oscuro')], default='system', max_length=10),
        ),
    ]
