# Generated by Django 5.2.17 on 2026-10-06 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.FileField(upload_to='menu-imports/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('processing', 'Procesando'), ('ready', 'Listo para revisar'), ('failed', 'Falló'), ('imported', 'Importado')], default='uploaded', max_length=16)),
                ('draft', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_imports', to='businesses.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
