# Generated by Django 5.2.17 on 2026-10-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_delivery_enabled_business_dine_in_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='brand_palette',
            field=models.CharField(choices=[('sunset', 'Naranja cálido'), ('ocean', 'Azul océano'), ('forest', 'Verde bosque'), ('grape', 'Morado uva'), ('rose', 'Rosa coral'), ('custom', 'Color personalizado')], default='sunset', max_length=16),
        ),
        migrations.AddField(
            model_name='business',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'En prueba'), ('active', 'Activo'), ('payment_due', 'Pago pendiente'), ('suspended', 'Suspendido'), ('canceled', 'Cancelado')], default='trial', max_length=16),
        ),
    ]
