# Generated by Django 5.2.17 on 2026-10-06 05:59

from django.db import migrations


def preserve_existing_palette(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    Business.objects.filter(brand_palette="sunset").update(brand_palette="custom")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_brand_palette_business_internal_notes_and_more'),
    ]

    operations = [
        migrations.RunPython(preserve_existing_palette, noop),
    ]
